/**
 * Static data loader — reads pre-fetched entity arrays from src/data/*.json.
 * These files are generated by: npm run sync:entities
 * Spanish translations live in src/data/es/*.json (generated by translate-entities).
 * The app never calls Halopedia directly — all data comes from these static files.
 */

import type { Character } from '../types/character';
import type { Weapon }    from '../types/weapon';
import type { Vehicle }   from '../types/vehicle';
import type { Race }      from '../types/race';
import type { Planet }    from '../types/planet';
import type { Game }      from '../types/game';
import type { Lang }      from '../contexts/LanguageContext';

// English (source of truth)
import _characters_en from '../data/characters.json' assert { type: 'json' };
import _weapons_en    from '../data/weapons.json'    assert { type: 'json' };
import _vehicles_en   from '../data/vehicles.json'   assert { type: 'json' };
import _races_en      from '../data/races.json'       assert { type: 'json' };
import _planets_en    from '../data/planets.json'     assert { type: 'json' };
import _games_en      from '../data/games.json'       assert { type: 'json' };

// Spanish (Latin American)
import _characters_es from '../data/es/characters.json' assert { type: 'json' };
import _weapons_es    from '../data/es/weapons.json'    assert { type: 'json' };
import _vehicles_es   from '../data/es/vehicles.json'   assert { type: 'json' };
import _races_es      from '../data/es/races.json'       assert { type: 'json' };
import _planets_es    from '../data/es/planets.json'     assert { type: 'json' };
import _games_es      from '../data/es/games.json'       assert { type: 'json' };

export async function fetchCharacters(lang: Lang = 'en'): Promise<Character[]> {
  return (lang === 'es' ? _characters_es : _characters_en) as Character[];
}

export async function fetchWeapons(lang: Lang = 'en'): Promise<Weapon[]> {
  return (lang === 'es' ? _weapons_es : _weapons_en) as Weapon[];
}

export async function fetchVehicles(lang: Lang = 'en'): Promise<Vehicle[]> {
  return (lang === 'es' ? _vehicles_es : _vehicles_en) as Vehicle[];
}

export async function fetchRaces(lang: Lang = 'en'): Promise<Race[]> {
  return (lang === 'es' ? _races_es : _races_en) as Race[];
}

export async function fetchPlanets(lang: Lang = 'en'): Promise<Planet[]> {
  return (lang === 'es' ? _planets_es : _planets_en) as Planet[];
}

export async function fetchGames(lang: Lang = 'en'): Promise<Game[]> {
  return (lang === 'es' ? _games_es : _games_en) as Game[];
}
