/**
 * Static data loader — reads pre-fetched entity arrays from src/data/*.json.
 * These files are generated by: npm run sync:entities
 * The app never calls Halopedia directly — all data comes from these static files.
 */

import type { Character } from '../types/character';
import type { Weapon } from '../types/weapon';
import type { Vehicle } from '../types/vehicle';
import type { Race } from '../types/race';
import type { Planet } from '../types/planet';
import type { Game } from '../types/game';

import _characters from '../data/characters.json' assert { type: 'json' };
import _weapons    from '../data/weapons.json'    assert { type: 'json' };
import _vehicles   from '../data/vehicles.json'   assert { type: 'json' };
import _races      from '../data/races.json'       assert { type: 'json' };
import _planets    from '../data/planets.json'     assert { type: 'json' };
import _games      from '../data/games.json'       assert { type: 'json' };

export async function fetchCharacters(): Promise<Character[]> {
  return _characters as Character[];
}

export async function fetchWeapons(): Promise<Weapon[]> {
  return _weapons as Weapon[];
}

export async function fetchVehicles(): Promise<Vehicle[]> {
  return _vehicles as Vehicle[];
}

export async function fetchRaces(): Promise<Race[]> {
  return _races as Race[];
}

export async function fetchPlanets(): Promise<Planet[]> {
  return _planets as Planet[];
}

export async function fetchGames(): Promise<Game[]> {
  return _games as Game[];
}
